# Generated by Django 2.0.7 on 2018-08-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0003_post_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
