# Generated by Django 2.0.7 on 2018-08-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0004_auto_20180808_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
