# Generated by Django 2.0.7 on 2018-08-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0005_post_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='cusine',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cusine',
            field=models.ManyToManyField(related_name='restaurants', to='foodblog.Cuisine'),
        ),
    ]
